[package]
name = "launchpad_hue"
version = "0.1.0"
authors = ["decentninja <encrypt.wave@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.7.0"
